apiVersion: v1
kind: Pod
metadata:
  name: labels-demo
  labels:
    Course: DevOps
    Cloud: AWS
    Master: krish
spec:
  containers:
  - name: label
    image: nginx
    ports:
    - containerPort: 80