apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: roboshop
spec:
  # list of containers
  containers:
  - name: sample-pod
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"