apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    iamge: nginx
    ports:
    - containerPort: 80
    env:
    - name: content
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: course
    - name: topics
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: tools